resolver: lts-12.5
extra-package-dbs: []
packages:
- '.'
- 'tests/test-package/'
extra-deps:
- haddock-api-2.20.0
- haddock-library-1.6.0
- hdocs-0.5.3.0
- hformat-0.3.3.0
- simple-log-0.9.6
- text-region-0.3.1.0
- haskell-names-0.9.2
flags: {}
