resolver: lts-11.10
extra-package-dbs: []
packages:
- '.'
- 'tests/test-package/'
extra-deps:
- haddock-api-2.18.1
- haddock-library-1.4.4
- hdocs-0.5.3.0
- aeson-lens-0.5.0.0
flags: {}
system-ghc: true
